### ISSUE TITLE
使用build.py

### ISSUE THREAD

**Issue by sadoneli** [mritd/koolshare-gdddns#2]
你好，收到了你得合并，当时没看清楚就合并了，但现在检查了下还不适合我们的要求，所以在https://github.com/koolshare/koolshare.github.io上进行了回滚

请使用build.py 配合config.json.js来生成插件包
config.json.js是推送到用户端重要的文件，里面的内容会在中转服务器内自动整合进https://koolshare.ngrok.wang/softcenter/app.json.js，此链接被用户的软件中心接受，判断软件的安装状态，版本号，软件的描述等

config.json.js版本号尤其重要，每次更新版本号后会，中转服务器会检测到更改，然后将config.json.js的内容合并到app.json.js，用户就会收到更新

**Comment by sadoneli** [comment]
另外独立插件的收录不是以submodule进行的，而是https://github.com/koolshare/koolshare.github.io/blob/acelan_softcenter_ui/softcenter/modules.json，中转服务器后台会检测modules.json，然后进行相应的收录

**Comment by mritd** [comment]
@sadoneli 好的 我看下 ！

**Comment by mritd** [comment]
@sadoneli 我看到 主仓库softcenter 下值有一个 build.sh 啊，这个 build.py 是放在哪的？
