### ISSUE TITLE
body好像得传数组

### ISSUE THREAD

**Issue by CodeInDreams** [mritd/koolshare-gdddns#4]
https://github.com/mritd/koolshare-gdddns/blob/3970e1bda10c2f3c6e69a92e83c3e60b0c3e2dc8/gdddns/scripts/gdddns_update.sh#L42
```
    -d "[{\"data\":\"$ip\",\"ttl\":$gdddns_ttl}]"
```

**Comment by mritd** [comment]
我周末看下

**Comment by mritd** [comment]
refs #5
